# Generated by Django 2.1.4 on 2018-12-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181226_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_checkout_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_return_date',
            field=models.DateField(blank=True),
        ),
    ]
