# Generated by Django 2.1.4 on 2018-12-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181227_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
