# Generated by Django 2.1.4 on 2018-12-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_checkout_date',
            new_name='checkout_date',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_return_date',
            new_name='return_date',
        ),
    ]
