# Generated by Django 2.1.4 on 2019-01-15 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20181227_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Resource')),
            ],
            bases=('books.resource',),
        ),
    ]
