# Generated by Django 2.1.4 on 2019-01-15 08:21

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190115_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/no_image.png', null=True, upload_to=books.models.Resource.get_image_path),
        ),
    ]
