# Generated by Django 2.1.4 on 2019-01-16 07:15

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20190115_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, default='/images/no_image.png', null=True, upload_to=books.models.Resource.get_image_path),
        ),
    ]
