# Generated by Django 2.1.4 on 2019-01-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20190116_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
